#version: "3"
#services:
  #www:
    #build: 
      #context: .
      #dockerfile: Dockerfile
    #ports:
      #- ${PORT-8000}:80  # Utilisez le port 80 pour Apache
    #environment:
      #DEBUG: 1
    #volumes:
      #- ./www:/var/www/html  # Montez votre page HTML dans le répertoire du serveur web
  #redis:
    #image: redis  # Changez l'image au besoin


version: "3"
services:
  www:
    build: www
    ports:
      - ${PORT-8000}:5000
    user: nobody
    environment:
      DEBUG: 1
      #DATE_NAISSANCE: "2000-01-01" 
    command: python counter.py
    volumes:
      - ./www:/src
  redis:
    image: redis  # Changez l'image au besoin

#version: "3"
#services:
  #www:
    #build:
      #context: /home/cytech/trw/Python_Docker
      #dockerfile: docker-compose.yaml  # Spécifie le nom du fichier Dockerfile
    #ports:
      #- "${PORT-8000}:5000"
    #user: nobody
    #environment:
      #DEBUG: "1"
    #command: python Calc_Age.py
    #volumes:
      #- ./www:/src
  #redis:
    #image: redis
#networks:
  #default:
    #external: 
      #name: localnet  # Indique que le réseau est externe
